version: '3.1'

services:
  db:
    image: postgres
    container_name: hackaton_db
    restart: always
    environment:
      POSTGRES_DB: hackaton
      POSTGRES_USER: devfloydbr
      POSTGRES_PASSWORD: devfloydbr

    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - backend

  ws-client:
    image: amritb/socketio-client-tool:latest
    ports:
      - '8080:8080'

networks:
  backend:
    driver: bridge
